### ISSUE TITLE
Why does it require internet connection to train?

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [janelia-cellmap/cellmap-segmentation-challenge#76]
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/cellmap-segmentation-challenge/src/cellmap_segmentation_challenge/utils/__init__.py", line 1, in <module>
    from .crops import (
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/cellmap-segmentation-challenge/src/cellmap_segmentation_challenge/utils/crops.py", line 147, in <module>
    TEST_CROPS = fetch_test_crop_manifest()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/cellmap-segmentation-challenge/src/cellmap_segmentation_challenge/utils/crops.py", line 58, in fetch_test_crop_manifest
    head, *rows = fs.cat_file(path).decode().splitlines()
                  ^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/fsspec/implementations/http.py", line 234, in _cat_file
    async with session.get(self.encode_url(url), **kw) as r:
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1400, in _create_direct_connection
    raise last_exc
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1369, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/2878EBCCAED823C6/PycharmProjects/cellmap/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1130, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [Network is unreachable]
```
The example training script require internet connection or it will output an exception. The dataset has already been pre-downloaded.

**Comment by rhoadesScholar** [comment]
Good catch. The goal was to always have the most up to date list, but this should fail gracefully.
